import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { Raleway } from "next/font/google";

const raleWay = Raleway({ subsets: ["vietnamese"] });

export const metadata = {
  title: "FIT | WOMEN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleWay.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
