export const text_gift = [
  "Chúc bạn mãi cute, dễ thương nè",
  "Một bông hoa hồng luôn cần được nâng niu và các bạn cũng vậy",
  "Môi bạn đang cười xinh ghê, tụi mình muốn thấy nó nhiều lần hơn nữa",
  "Mình tin không có con gái nào xấu hết, còn nữ nhà FIT thì chắc chắn là xinh á",
  "Nếu xinh đẹp là lỗi thì bạn chính là bug đó",
  "Nơi ấm nhất không phải Mặt trời, mà là nụ cười của bạn!",
  "Hôm nay bạn rất xinh nhưng ngày mai sẽ khác, bạn sẽ còn xinh hơn á",
  "Mình có khả năng nhìn thấy tương lai, mình thấy kì này bạn full A+ luôn kìa",
  "Bạn chính là bông hoa đẹp nhất dù cho có hoa hay không nè",
  "Thế giới này có muôn vạn loài hoa, nhưng cậu là đoá hoa rực rỡ nhất!",
  "Mong bạn sẽ hạnh phúc mỗi ngày luôn chứ không chỉ ngày hôm nay nhen",
  "1,2,3,5,... ôi không, cậu đánh rơi nụ cười nơi tim tớ rồi!",
  "Nếu bạn không có hoa thì không sao, bạn đã luôn là bông hoa xinh đẹp nhất rồi đó",
  "Tụi mình không tặng hoa đâu, chẳng ai lại đi tặng hoa cho một bông hoa hết á",
  "Bạn là những điều tốt đẹp nhất mà trời cao ban tặng cho nhà FIT",
  "Đã là một bóng hồng nhà FIT, tớ mong trên môi bạn luôn nở nụ cười rạng ngời",
  "Bạn ơi, hãy sống với vẻ đẹp của mình và nở rộ như một bông hoa nha",
  "Tụi mình khỏi phải tới New York vẫn được gặp quá trời nữ thần nè",
  "Đôi mắt bạn không phải để khóc, mà hãy để nó ghi sâu những hình ảnh mà chúng tôi săn sóc cho bạn",
  "Nụ cười của bạn làm trái tim tụi mình tan chảy rồi đó",
];
